config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :departments, :path => 'formats' do
    resources :scripts, only: [:new, :create, :index]
  end
  root to: "static#home"
  resources :scripts

  get 'loglines', to: 'scripts#sort_loglines'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :scripts
    has_many :users, through: :scripts
    validates :name, presence: true, uniqueness: true
    
    accepts_nested_attributes_for :users, :scripts, reject_if: :all_blank
end

app/models/script.rb
class Script < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    belongs_to :department
    belongs_to :user

    accepts_nested_attributes_for :user, :department, reject_if: :all_blank

    def department_name
        self.department ? self.department.name : "Format Not Available"
    end

    scope :order_by_length, -> {
        Script.order("LENGTH(logline) ASC").limit(3)
    }   


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :scripts
  has_many :departments, through: :scripts

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   
      user.image = auth.info.image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    before_action :require_login
    def index
        @departments = Department.all
    end

    def show
        @department = Department.find_by_id(params[:id])
    end


    def new
        @department = Department.new
        @department.scripts.build
      end
    
      def create
        @department = Department.new(department_params)
    
        if @department.valid? 
          @department.save
          redirect_to departments_path
        else
          flash.now[:error] = @department.errors.full_messages
          render :new
        end
      end
    
      private
    
        def department_params
          params.require(:department).permit(
            :name, :script_id, :user_id,
            scripts_attributes: [:title, :logline, :user_id],
          )
        end

        def require_login
            unless user_signed_in?
              redirect_to new_user_session_path 
            end
          end
    end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
    before_action :require_login
    before_action :find_department, only: [:index, :new, :create, :show] 
    before_action :find_script, only: [:show, :edit, :update, :destroy]
 
    def index
        if @department
            @scripts = @department.scripts
        else
            @scripts = Script.all 
        end
    end

    def show
        # require_login, # find_department, # find_script
    end

    def new
        if @department 
            @script = @department.scripts.build
            render :new_department_script
        else
        @script = current_user.scripts.build
        end
    end

    def create
        @script = current_user.scripts.build(script_params)
        if @script.valid?
            @script.save
            redirect_to scripts_path
        else
            flash.now[:error] = @script.errors.full_messages
            if @department
                render :new_department_script
            else
            render :new
            end
        end
    end

    def edit
        # require_login, # find_script
    end

    def update
        if @script.update(script_params)
            redirect_to script_path(@script)
        else
            flash.now[:error] = @script.errors.full_messages
            render :edit
        end
    end

    def destroy
        @script.destroy
        flash[:notice] = "#{@script.title} was deleted."
        redirect_to scripts_path
    end

    def sort_loglines
        @scripts = Script.order_by_length
    end

  

    private
    def find_script
        @script = Script.find_by_id(params[:id])
    end

    def find_department
        if params[:department_id]
            @department = Department.find_by_id(params[:department_id])
        end
    end

    def script_params
        params.require(:script).permit(:title, :department_id, :user_id, :logline, department_attributes:[:name])
    end

    def require_login
        unless user_signed_in?
          redirect_to new_user_session_path 
        end
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper

    def render_nav_links
        content_tag("ul") do
            if user_signed_in? # is logged in
                content_tag("li") do
                    link_to("Home", root_path)
                end +

                content_tag("li") do
                  link_to("Scripts", scripts_path)
                end + 

                content_tag("li") do
                  link_to("Add Script", new_script_path)
                end +

                content_tag("li") do
                    link_to("Formats", departments_path)
                end +

                content_tag("li") do
                    link_to("Add a Format", new_department_path)
                end +

                content_tag("li") do
                    link_to("Log Out", destroy_user_session_path)
                end 
            else # is logged out
                content_tag("li") do
                    link_to("Home", root_path)
                end +
                content_tag("li") do
                    link_to("Log In", new_user_session_path)
                end + 
                content_tag("li") do
                   
                end
            end
          end
    end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/departments/index.html.erb
<h1>List of All Formats</h1>

<table>
    <tr>
    <% @departments.each do |department| %>
        <td><%= link_to department.name, department_path(department), :class => "link_to_style" %></td>
    </tr>
    <% end %>
    
</table>
<%= button_to "Add a Format", new_department_path, :method => "get" %>

app/views/departments/new.html.erb
<h1>Add Format</h1>

<%= form_for @department do |f| %>
    <div>
        <%= f.label :name, "Format:" %>
        <%= f.text_field :name, :autocomplete => :off %>
    </div>
        <br>

        <%= f.submit "Add Format" %>
<% end %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

<p style="text-align: center"></p>

<table>
    <tr>
        <td><b>Name:</b></td>
        <td><%= @department.name %></td>
    </tr>
    <tr>
        <td><b>List of Scripts:</b></td>
        <td><%= link_to "Full List Here", department_scripts_path(@department) %></td>
    </tr>
</table>
<%= button_to "Add a Script", new_department_script_path(@department), :method => "get" %>

app/views/layouts/_errors.html.erb
<!-- flash errors -->
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <p style="background-color: #def4ef; text-align: center"><%= error %></p>
      <% end %>
    <% end %>
  <!-- flash notice: delete -->
    <%= content_tag("p", flash[:notice]) if flash[:notice] %>

app/views/layouts/_nav.html.erb
<style>

    ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #18453B;

    }

    li {
    float: left;
    }

    li a {
    display: block;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
        color: #fdfbfa;
        font-family: 'Merriweather', serif;
        font-size: 18px;
    }

    li a:hover {
    background-color: #266b5b;
    }


    body {
        margin: 0;
    }

   

</style>

<nav>
    <%= render_nav_links %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Green Light</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
<%= render 'layouts/nav' %>
  <div class="row">
    <div class="column side"></div>
    <div class="column middle">
<%= render 'layouts/errors' %>
  
        <%= yield %>
    </div>
    <div class="column side"></div>

  </body>
</html>

app/views/scripts/_form.html.erb
<%= form_for script do |f| %>
    <div>
        <%= f.label :title, "Title:"  %>
        <%= f.text_field :title, :autocomplete => :off %>
    </div>

    <div>
        <%= f.label :logline, "Logline:"  %>
        <%= f.text_field :logline, :autocomplete => :off %>
    </div>

    <h3>Select Format</h3>
    <div>
        <%= f.collection_select :department_id, Department.all, :id, :name, include_blank: "Select Format" %>
    </div>

    <%= hidden_field_tag :user_id, current_user.id %>
    <%= f.submit button_name %>
<% end %>

app/views/scripts/edit.html.erb
<h1>Edit <%= @script.title %></h1>

<%= render partial: "form", locals: { script: @script, button_name: "Edit Script"} %>

app/views/scripts/index.html.erb
<h1><%= "#{@department.name}" if @department %> Scripts</h1>
<table>
    <tr>
        <th>Title</th>
        <th>Logline</th>
        <th>Format</th>
    </tr>

    <tr>
    <% @scripts.each do |script| %>
        <td><%= link_to script.title, script_path(script), :class => "link_to_style" %></td>
        <td><%= script.logline %></td>
        <td><%= script.department_name %></td>
    </tr>
    <% end %>
</table>

<%= button_to "Add a Script", new_script_path, :method => "get" %>
<%= button_to "See Scripts with Shortest Loglines", loglines_path, :method => "get" %>

app/views/scripts/new.html.erb
<h1>Add a Script</h1>

<%= render partial: "form", locals: { script: @script, button_name: "Add Script"} %>

app/views/scripts/new_department_script.html.erb
<h1><%= "Add a New #{@department.name} Script" %></h1>

<%= form_for [@department, @script] do |f| %>
    <div>
        <%= f.label :title, "Title:"  %>
        <%= f.text_field :title, :autocomplete => :off %>
    </div>

    <div>
        <%= f.label :logline, "Logline:"  %>
        <%= f.text_field :logline, :autocomplete => :off %>
    </div>
    <%= f.hidden_field :department_id %>
    <%= f.submit "Add Script" %>
<% end %>

app/views/scripts/show.html.erb
<h1><%= @script.title %></h1>
<table>
    <tr>
        <td><b>Title:</b></td>
        <td><%= @script.title %></td>
    </tr>

    <tr>
        <td><b>Logline:</b></td>
        <td><%= @script.logline %></td>
    </tr>

    <tr>
        <td><b>Format:</b></td>
        <td><%= @script.department_name %></td>
    </tr>
</table>
<br>
<%= button_to "Edit", edit_script_path(@script), :method => "get" %>
<br>
<%= button_to "Delete", script_path(@script), :method => "delete" %>

app/views/scripts/sort_loglines.html.erb
<h1>Speed Pitches</h1>
<h3>Scripts with the shortest loglines</h3>

<table>
    <tr>
        <th>Title</th>
        <th>Logline</th>
        <th>Format</th>
    </tr>

    <tr>
    <% @scripts.each do |script| %>
        <td><%= link_to script.title, script_path(script), :class => "link_to_style" %></td>
        <td><%= script.logline %></td>
        <td><%= script.department_name %></td>
    </tr>
    <% end %>
</table>